services:
  jbpm-demo-web:
    build:
      target: development
    image: jbpm-demo-web-development
    container_name: jbpm-demo-web-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./package.json:/home/node/package.json
