services:
  jbpm-demo-web:
    build:
      target: development
    image: jbpm-demo-web-development
    container_name: jbpm-demo-web-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
  jbpm-server:
    ports:
      - "8080:8080"
      - "8001:8001"
