services:
  hapi-template:
    build:
      target: development
    image: hapi-template-development
    container_name: hapi-template-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
